// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PlayerInfo.proto

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type State int32

const (
	State_NONE    State = 0
	State_IDLE    State = 1
	State_WALK    State = 2
	State_RUN     State = 3
	State_JUMP    State = 4
	State_FLY     State = 5
	State_SWIM    State = 7
	State_ATTACK  State = 8
	State_HURT    State = 9
	State_SKILL   State = 10
	State_DIE     State = 11
	State_LINEOFF State = 12
	State_SPRINT  State = 13
	State_ROTATE  State = 14
)

var State_name = map[int32]string{
	0:  "NONE",
	1:  "IDLE",
	2:  "WALK",
	3:  "RUN",
	4:  "JUMP",
	5:  "FLY",
	7:  "SWIM",
	8:  "ATTACK",
	9:  "HURT",
	10: "SKILL",
	11: "DIE",
	12: "LINEOFF",
	13: "SPRINT",
	14: "ROTATE",
}
var State_value = map[string]int32{
	"NONE":    0,
	"IDLE":    1,
	"WALK":    2,
	"RUN":     3,
	"JUMP":    4,
	"FLY":     5,
	"SWIM":    7,
	"ATTACK":  8,
	"HURT":    9,
	"SKILL":   10,
	"DIE":     11,
	"LINEOFF": 12,
	"SPRINT":  13,
	"ROTATE":  14,
}

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}
func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (x *State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(State_value, data, "State")
	if err != nil {
		return err
	}
	*x = State(value)
	return nil
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type StatusInfo struct {
	Userid           *string `protobuf:"bytes,1,req,name=Userid" json:"Userid,omitempty"`
	TargetPos        *Vect3  `protobuf:"bytes,2,opt,name=TargetPos" json:"TargetPos,omitempty"`
	TranSpeed        *int32  `protobuf:"varint,3,opt,name=TranSpeed" json:"TranSpeed,omitempty"`
	SpawnPos         *Vect2  `protobuf:"bytes,4,opt,name=SpawnPos" json:"SpawnPos,omitempty"`
	Status           *State  `protobuf:"varint,5,opt,name=Status,enum=msg.State,def=0" json:"Status,omitempty"`
	FrameIndex       *int64  `protobuf:"varint,6,req,name=FrameIndex" json:"FrameIndex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusInfo) Reset()                    { *m = StatusInfo{} }
func (m *StatusInfo) String() string            { return proto.CompactTextString(m) }
func (*StatusInfo) ProtoMessage()               {}
func (*StatusInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

const Default_StatusInfo_Status State = State_NONE

func (m *StatusInfo) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *StatusInfo) GetTargetPos() *Vect3 {
	if m != nil {
		return m.TargetPos
	}
	return nil
}

func (m *StatusInfo) GetTranSpeed() int32 {
	if m != nil && m.TranSpeed != nil {
		return *m.TranSpeed
	}
	return 0
}

func (m *StatusInfo) GetSpawnPos() *Vect2 {
	if m != nil {
		return m.SpawnPos
	}
	return nil
}

func (m *StatusInfo) GetStatus() State {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_StatusInfo_Status
}

func (m *StatusInfo) GetFrameIndex() int64 {
	if m != nil && m.FrameIndex != nil {
		return *m.FrameIndex
	}
	return 0
}

type PlayerInfo struct {
	Userid           *string `protobuf:"bytes,1,req,name=Userid" json:"Userid,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=Nickname" json:"Nickname,omitempty"`
	Level            *int32  `protobuf:"varint,3,opt,name=Level" json:"Level,omitempty"`
	Status           *State  `protobuf:"varint,4,opt,name=Status,enum=msg.State,def=0" json:"Status,omitempty"`
	FrameIndex       *int32  `protobuf:"varint,5,opt,name=FrameIndex" json:"FrameIndex,omitempty"`
	SpawnPos         *Vect2  `protobuf:"bytes,6,opt,name=SpawnPos" json:"SpawnPos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

const Default_PlayerInfo_Status State = State_NONE

func (m *PlayerInfo) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *PlayerInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *PlayerInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerInfo) GetStatus() State {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_PlayerInfo_Status
}

func (m *PlayerInfo) GetFrameIndex() int32 {
	if m != nil && m.FrameIndex != nil {
		return *m.FrameIndex
	}
	return 0
}

func (m *PlayerInfo) GetSpawnPos() *Vect2 {
	if m != nil {
		return m.SpawnPos
	}
	return nil
}

type Vect2 struct {
	X                *float32 `protobuf:"fixed32,1,req,name=X" json:"X,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Vect2) Reset()                    { *m = Vect2{} }
func (m *Vect2) String() string            { return proto.CompactTextString(m) }
func (*Vect2) ProtoMessage()               {}
func (*Vect2) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Vect2) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vect2) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Vect3 struct {
	X                *int32 `protobuf:"varint,1,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=Y" json:"Y,omitempty"`
	Z                *int32 `protobuf:"varint,3,req,name=Z" json:"Z,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Vect3) Reset()                    { *m = Vect3{} }
func (m *Vect3) String() string            { return proto.CompactTextString(m) }
func (*Vect3) ProtoMessage()               {}
func (*Vect3) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Vect3) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Vect3) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Vect3) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*StatusInfo)(nil), "msg.StatusInfo")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*Vect2)(nil), "msg.Vect2")
	proto.RegisterType((*Vect3)(nil), "msg.Vect3")
	proto.RegisterEnum("msg.State", State_name, State_value)
}

func init() { proto.RegisterFile("PlayerInfo.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xbd, 0x8e, 0x9b, 0x40,
	0x14, 0x85, 0x33, 0xc0, 0x60, 0xb8, 0xce, 0x5a, 0x37, 0x53, 0x51, 0x64, 0x25, 0x44, 0x85, 0x52,
	0xb8, 0xd8, 0xed, 0xd2, 0xa1, 0x18, 0x94, 0x89, 0x31, 0x46, 0x30, 0xc4, 0x71, 0x3a, 0x64, 0x4f,
	0x2c, 0x2b, 0x06, 0x2c, 0x20, 0x7f, 0x8f, 0x91, 0x36, 0x65, 0x9e, 0x34, 0x1a, 0x6c, 0x09, 0xc9,
	0x6e, 0xd2, 0x7d, 0x3a, 0x47, 0x47, 0xf7, 0xbb, 0x80, 0xe9, 0xa9, 0xfc, 0x25, 0x5b, 0x5e, 0x7f,
	0x69, 0xe6, 0xe7, 0xb6, 0xe9, 0x1b, 0xa6, 0x57, 0xdd, 0xc1, 0xfb, 0x4b, 0x00, 0xf2, 0xbe, 0xec,
	0xbf, 0x75, 0xaa, 0x61, 0x33, 0x30, 0x8b, 0x4e, 0xb6, 0xc7, 0xbd, 0x43, 0x5c, 0xcd, 0xb7, 0xd9,
	0x23, 0xd8, 0xa2, 0x6c, 0x0f, 0xb2, 0x4f, 0x9b, 0xce, 0xd1, 0x5c, 0xe2, 0x4f, 0x9f, 0x60, 0x5e,
	0x75, 0x87, 0xf9, 0x47, 0xb9, 0xeb, 0x9f, 0xd9, 0x2b, 0xb0, 0x45, 0x5b, 0xd6, 0xf9, 0x59, 0xca,
	0xbd, 0xa3, 0xbb, 0xc4, 0xa7, 0xec, 0x35, 0x58, 0xf9, 0xb9, 0xfc, 0x51, 0xab, 0x81, 0x71, 0x33,
	0x78, 0x62, 0x2e, 0x98, 0x97, 0x6b, 0x0e, 0x75, 0x89, 0x3f, 0xbb, 0x76, 0x2a, 0x92, 0x6f, 0x8d,
	0x64, 0x9d, 0x84, 0x8c, 0x01, 0x44, 0x6d, 0x59, 0x49, 0x5e, 0xef, 0xe5, 0x4f, 0xc7, 0x74, 0x35,
	0x5f, 0xf7, 0x7e, 0x13, 0x80, 0x51, 0xff, 0x4e, 0x12, 0xc1, 0x4a, 0x8e, 0xbb, 0xaf, 0x75, 0x59,
	0xc9, 0xc1, 0xd1, 0x66, 0x0f, 0x40, 0x63, 0xf9, 0x5d, 0x9e, 0xae, 0x4e, 0xe3, 0x55, 0xe3, 0xbf,
	0xae, 0xd2, 0xbb, 0x4f, 0xcc, 0xdb, 0x4f, 0xbc, 0x47, 0xa0, 0x97, 0x97, 0x6c, 0x20, 0x9f, 0x06,
	0x11, 0x4d, 0xe1, 0xd6, 0xd1, 0x14, 0x7a, 0xfe, 0xa5, 0x7e, 0x1e, 0x6b, 0x3a, 0xd6, 0x03, 0x7e,
	0x76, 0x74, 0x85, 0x6f, 0xfe, 0x10, 0xa0, 0x83, 0x0a, 0xb3, 0x60, 0x90, 0xc1, 0x17, 0x8a, 0xf8,
	0x22, 0x0e, 0x91, 0x28, 0xda, 0x04, 0xf1, 0x12, 0x35, 0x36, 0x01, 0x3d, 0x2b, 0x12, 0xd4, 0x55,
	0xf4, 0xa1, 0x58, 0xa5, 0x68, 0xa8, 0x28, 0x8a, 0xb7, 0x48, 0x55, 0x94, 0x6f, 0xf8, 0x0a, 0x27,
	0x0c, 0xc0, 0x0c, 0x84, 0x08, 0xde, 0x2d, 0xd1, 0x52, 0xe9, 0xfb, 0x22, 0x13, 0x68, 0x33, 0x1b,
	0x68, 0xbe, 0xe4, 0x71, 0x8c, 0xa0, 0x36, 0x0b, 0x1e, 0xe2, 0x94, 0x4d, 0x61, 0x12, 0xf3, 0x24,
	0x5c, 0x47, 0x11, 0xbe, 0x54, 0xb3, 0x3c, 0xcd, 0x78, 0x22, 0xf0, 0x41, 0x71, 0xb6, 0x16, 0x81,
	0x08, 0x71, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x73, 0x7b, 0x5e, 0x36, 0x02, 0x00, 0x00,
}
